### ISSUE TITLE
☂️ Navigation bar

### ISSUE THREAD

**Issue by chanhihi** [LastExTrascendence/frontend#7]
## Side Navigation Bar
- [x] #5 
- [x] LeftSide Link navbar of side navigation bar
- [x] RightSide Follow List of side navigation bar
- [x] RightSide Follow List Option List(Profile, DM, Unfollow, Block)
- #22 
- [x] #74
--- 

## Top Navigation Bar
- [x] #13
- [ ] usersearch form
